import 'dotenv/config';
import { PrismaClient, Role } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import * as bcrypt from 'bcrypt';
import { Pool } from 'pg';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const seededDoctors = [
  {
    id: 'doc-6',
    email: 'sunita.deshmukh@sehatsetu.com',
    name: 'Dr. Sunita Deshmukh',
    specialty: 'General Physician',
    experience: '11+ Years Experience',
    rating: 4.8,
    reviewsCount: 230,
    hospital: 'Apollo Medical Center',
    location: 'Delhi',
    imageUrl: 'https://images.unsplash.com/photo-1594824813566-88855376a911?auto=format&fit=crop&q=80&w=400',
    fee: '₹500',
    consultationFee: 500,
    availableToday: true,
    priorityLevel: 'P1',
    priorityScore: 200,
    degrees: 'MBBS, MD - General Medicine',
    tags: ['General Physician', 'Primary Care', 'Fever & Cold', 'Instant Consult'],
  },
  {
    id: 'doc-11',
    email: 'ananya.sharma@sehatsetu.com',
    name: 'Dr. Ananya Sharma',
    specialty: 'Dermatologist',
    experience: '8+ Years Experience',
    rating: 4.7,
    reviewsCount: 180,
    hospital: 'Fortis Hospital',
    location: 'Mumbai',
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400',
    fee: '₹600',
    consultationFee: 600,
    availableToday: true,
    priorityLevel: 'P1',
    priorityScore: 195,
    degrees: 'MBBS, MD - Dermatology',
    tags: ['Skin & Laser', 'Dermatology Expert'],
  },
  {
    id: 'doc-1',
    email: 'alok.verma@sehatsetu.com',
    name: 'Dr. Alok Verma',
    specialty: 'Pediatrician',
    experience: '10+ Years Experience',
    rating: 4.9,
    reviewsCount: 310,
    hospital: 'Max Super Speciality Hospital',
    location: 'Noida',
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    fee: '₹500',
    consultationFee: 500,
    availableToday: true,
    priorityLevel: 'P2',
    priorityScore: 100,
    degrees: 'MBBS, DCH - Pediatrics',
    tags: ['Child Care', 'Pediatrician Specialist'],
  },
  {
    id: 'doc-2',
    email: 'priya.mehta@sehatsetu.com',
    name: 'Dr. Priya Mehta',
    specialty: 'Gynecologist',
    experience: '9+ Years Experience',
    rating: 4.8,
    reviewsCount: 210,
    hospital: 'Kokilaben Hospital',
    location: 'Mumbai',
    imageUrl: 'https://images.unsplash.com/photo-1594824813566-88855376a911?auto=format&fit=crop&q=80&w=400',
    fee: '₹600',
    consultationFee: 600,
    availableToday: false,
    priorityLevel: 'P3',
    priorityScore: 75,
    degrees: 'MBBS, DGO - Gynecology',
    tags: ['Women Health', 'Obstetrics Specialist'],
  },
  {
    id: 'doc-3',
    email: 'amit.verma@sehatsetu.com',
    name: 'Dr. Amit Verma',
    specialty: 'Neurologist',
    experience: '15+ Years Experience',
    rating: 4.9,
    reviewsCount: 450,
    hospital: 'Neuro Care Hospital',
    location: 'Pune',
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400',
    fee: '₹1200',
    consultationFee: 1200,
    availableToday: false,
    priorityLevel: 'P2',
    priorityScore: 90,
    degrees: 'MBBS, DM - Neurology',
    tags: ['HOD', 'Brain & Nerve Expert'],
  },
  {
    id: 'doc-5',
    email: 'rajesh.gupta@sehatsetu.com',
    name: 'Dr. Rajesh Gupta',
    specialty: 'Orthopedic Doctor',
    experience: '14+ Years Experience',
    rating: 4.9,
    reviewsCount: 510,
    hospital: 'Apex Spine & Joint Institute',
    location: 'Hyderabad',
    imageUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=400',
    fee: '₹1000',
    consultationFee: 1000,
    availableToday: true,
    priorityLevel: 'P2',
    priorityScore: 88,
    degrees: 'MBBS, MS - Orthopedics',
    tags: ['Joint Replacement Specialist'],
  },
  {
    id: 'doc-9',
    email: 'meera.nambiar@sehatsetu.com',
    name: 'Dr. Meera Nambiar',
    specialty: 'Ophthalmologist',
    experience: '13+ Years Experience',
    rating: 4.8,
    reviewsCount: 340,
    hospital: 'Vision Eye Institute',
    location: 'Pune',
    imageUrl: 'https://images.unsplash.com/photo-1594824813566-88855376a911?auto=format&fit=crop&q=80&w=400',
    fee: '₹750',
    consultationFee: 750,
    availableToday: true,
    priorityLevel: 'P3',
    priorityScore: 78,
    degrees: 'MBBS, MS - Ophthalmology',
    tags: ['Cataract & Lasik'],
  },
  {
    id: 'doc-4',
    email: 'vikramaditya.roy@sehatsetu.com',
    name: 'Dr. Vikramaditya Roy',
    specialty: 'Cardiologist',
    experience: '18+ Years Experience',
    rating: 4.95,
    reviewsCount: 620,
    hospital: 'Escorts Heart Institute',
    location: 'Delhi',
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400',
    fee: '₹1500',
    consultationFee: 1500,
    availableToday: true,
    priorityLevel: 'P2',
    priorityScore: 180,
    degrees: 'MBBS, DM - Cardiology',
    tags: ['Heart Specialist', 'Angioplasty Expert'],
  },
  {
    id: 'doc-7',
    email: 'kavita.reddy@sehatsetu.com',
    name: 'Dr. Kavita Reddy',
    specialty: 'Dentist',
    experience: '7+ Years Experience',
    rating: 4.75,
    reviewsCount: 195,
    hospital: 'Clove Dental Clinic',
    location: 'Bengaluru',
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400',
    fee: '₹400',
    consultationFee: 400,
    availableToday: true,
    priorityLevel: 'P4',
    priorityScore: 65,
    degrees: 'BDS, MDS - Orthodontics',
    tags: ['Dental Surgery', 'Root Canal'],
  },
  {
    id: 'doc-8',
    email: 'suresh.menon@sehatsetu.com',
    name: 'Dr. Suresh Menon',
    specialty: 'ENT Specialist',
    experience: '12+ Years Experience',
    rating: 4.85,
    reviewsCount: 280,
    hospital: 'Manipal Hospital',
    location: 'Bengaluru',
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    fee: '₹700',
    consultationFee: 700,
    availableToday: true,
    priorityLevel: 'P3',
    priorityScore: 82,
    degrees: 'MBBS, MS - ENT',
    tags: ['Ear Nose Throat', 'Sinus Surgery'],
  },
  {
    id: 'doc-10',
    email: 'tarun.bhatia@sehatsetu.com',
    name: 'Dr. Tarun Bhatia',
    specialty: 'Psychiatrist',
    experience: '10+ Years Experience',
    rating: 4.9,
    reviewsCount: 310,
    hospital: 'MindCare Wellness',
    location: 'Delhi',
    imageUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=400',
    fee: '₹1000',
    consultationFee: 1000,
    availableToday: false,
    priorityLevel: 'P3',
    priorityScore: 85,
    degrees: 'MBBS, MD - Psychiatry',
    tags: ['Mental Health', 'Anxiety & Depression'],
  },
  {
    id: 'doc-12',
    email: 'neha.saxena@sehatsetu.com',
    name: 'Dr. Neha Saxena',
    specialty: 'Pulmonologist',
    experience: '9+ Years Experience',
    rating: 4.8,
    reviewsCount: 220,
    hospital: 'Medanta Respiratory Care',
    location: 'Gurugram',
    imageUrl: 'https://images.unsplash.com/photo-1594824813566-88855376a911?auto=format&fit=crop&q=80&w=400',
    fee: '₹900',
    consultationFee: 900,
    availableToday: true,
    priorityLevel: 'P3',
    priorityScore: 80,
    degrees: 'MBBS, DTCD - Pulmonology',
    tags: ['Asthma Care', 'Lung Specialist'],
  },
  {
    id: 'doc-13',
    email: 'arvind.swamy@sehatsetu.com',
    name: 'Dr. Arvind Swamy',
    specialty: 'Gastroenterologist',
    experience: '16+ Years Experience',
    rating: 4.92,
    reviewsCount: 480,
    hospital: 'Asian Institute of Gastroenterology',
    location: 'Hyderabad',
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400',
    fee: '₹1100',
    consultationFee: 1100,
    availableToday: true,
    priorityLevel: 'P2',
    priorityScore: 92,
    degrees: 'MBBS, DM - Gastroenterology',
    tags: ['Digestive Diseases', 'Endoscopy Expert'],
  },
  {
    id: 'doc-14',
    email: 'shilpa.iyer@sehatsetu.com',
    name: 'Dr. Shilpa Iyer',
    specialty: 'Endocrinologist',
    experience: '11+ Years Experience',
    rating: 4.86,
    reviewsCount: 290,
    hospital: 'Thyrocare & Endocrine Center',
    location: 'Mumbai',
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400',
    fee: '₹850',
    consultationFee: 850,
    availableToday: false,
    priorityLevel: 'P3',
    priorityScore: 84,
    degrees: 'MBBS, DM - Endocrinology',
    tags: ['Diabetes Specialist', 'Thyroid Care'],
  },
  {
    id: 'doc-15',
    email: 'rohan.kulkarni@sehatsetu.com',
    name: 'Dr. Rohan Kulkarni',
    specialty: 'Urologist',
    experience: '13+ Years Experience',
    rating: 4.88,
    reviewsCount: 360,
    hospital: 'Ruby Hall Clinic',
    location: 'Pune',
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    fee: '₹950',
    consultationFee: 950,
    availableToday: true,
    priorityLevel: 'P3',
    priorityScore: 86,
    degrees: 'MBBS, MCh - Urology',
    tags: ['Kidney Care', 'Urology Specialist'],
  },
];

const seededPatients = [
  {
    email: 'patient@example.com',
    fullName: 'Rahul Sharma',
    gender: 'Male',
    phone: '+91 98765 43210',
    age: '28',
    height: '175 cm',
    weight: '72 kg',
    bloodGroup: 'O+',
    emergencyContact: '+91 98111 22233',
    allergies: ['Dust', 'Penicillin'],
    chronicConditions: ['Mild Asthma'],
  },
  {
    email: 'ananya.patient@sehatsetu.com',
    fullName: 'Ananya Sharma',
    gender: 'Female',
    phone: '+91 91234 56789',
    age: '26',
    height: '162 cm',
    weight: '55 kg',
    bloodGroup: 'B+',
    emergencyContact: '+91 99887 76655',
    allergies: ['Pollen'],
    chronicConditions: ['Migraine'],
  },
];

async function main() {
  const passwordHash = await bcrypt.hash('password123', 10);

  // 1. Seed 15 doctors
  for (const docData of seededDoctors) {
    const user = await prisma.user.upsert({
      where: { email: docData.email },
      update: {
        fullName: docData.name,
      },
      create: {
        email: docData.email,
        fullName: docData.name,
        passwordHash,
        role: Role.DOCTOR,
      },
    });

    await prisma.doctor.upsert({
      where: { userId: user.id },
      update: {
        name: docData.name,
        specialty: docData.specialty,
        experience: docData.experience,
        rating: docData.rating,
        reviewsCount: docData.reviewsCount,
        hospital: docData.hospital,
        location: docData.location,
        imageUrl: docData.imageUrl,
        fee: docData.fee,
        consultationFee: docData.consultationFee,
        availableToday: docData.availableToday,
        priorityLevel: docData.priorityLevel,
        priorityScore: docData.priorityScore,
        degrees: docData.degrees,
        tags: docData.tags,
      },
      create: {
        id: docData.id,
        userId: user.id,
        name: docData.name,
        specialty: docData.specialty,
        experience: docData.experience,
        rating: docData.rating,
        reviewsCount: docData.reviewsCount,
        hospital: docData.hospital,
        location: docData.location,
        imageUrl: docData.imageUrl,
        fee: docData.fee,
        consultationFee: docData.consultationFee,
        availableToday: docData.availableToday,
        priorityLevel: docData.priorityLevel,
        priorityScore: docData.priorityScore,
        degrees: docData.degrees,
        tags: docData.tags,
      },
    });
  }

  // 2. Seed Patients
  for (const patientData of seededPatients) {
    const patientUser = await prisma.user.upsert({
      where: { email: patientData.email },
      update: {
        fullName: patientData.fullName,
      },
      create: {
        email: patientData.email,
        fullName: patientData.fullName,
        passwordHash,
        role: Role.PATIENT,
      },
    });

    await prisma.patient.upsert({
      where: { userId: patientUser.id },
      update: {
        phone: patientData.phone,
        gender: patientData.gender,
        age: patientData.age,
        height: patientData.height,
        weight: patientData.weight,
        bloodGroup: patientData.bloodGroup,
        emergencyContact: patientData.emergencyContact,
        allergies: patientData.allergies,
        chronicConditions: patientData.chronicConditions,
      },
      create: {
        userId: patientUser.id,
        phone: patientData.phone,
        gender: patientData.gender,
        age: patientData.age,
        height: patientData.height,
        weight: patientData.weight,
        bloodGroup: patientData.bloodGroup,
        emergencyContact: patientData.emergencyContact,
        allergies: patientData.allergies,
        chronicConditions: patientData.chronicConditions,
      },
    });
  }

  console.log('Database seeded successfully with 15 Doctors and Patient profiles! 🌱');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
